/*
 * j-lawyer-io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * RestfulCaseV1
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-14T23:02:59.563495701+01:00[Europe/Berlin]")
public class RestfulCaseV1 {
  public static final String SERIALIZED_NAME_ARCHIVED = "archived";
  @SerializedName(SERIALIZED_NAME_ARCHIVED)
  private Integer archived;

  public static final String SERIALIZED_NAME_ASSISTANT = "assistant";
  @SerializedName(SERIALIZED_NAME_ASSISTANT)
  private java.lang.String assistant;

  public static final String SERIALIZED_NAME_CLAIM_NUMBER = "claimNumber";
  @SerializedName(SERIALIZED_NAME_CLAIM_NUMBER)
  private java.lang.String claimNumber;

  public static final String SERIALIZED_NAME_CLAIM_VALUE = "claimValue";
  @SerializedName(SERIALIZED_NAME_CLAIM_VALUE)
  private BigDecimal claimValue;

  public static final String SERIALIZED_NAME_CUSTOM1 = "custom1";
  @SerializedName(SERIALIZED_NAME_CUSTOM1)
  private java.lang.String custom1;

  public static final String SERIALIZED_NAME_CUSTOM2 = "custom2";
  @SerializedName(SERIALIZED_NAME_CUSTOM2)
  private java.lang.String custom2;

  public static final String SERIALIZED_NAME_CUSTOM3 = "custom3";
  @SerializedName(SERIALIZED_NAME_CUSTOM3)
  private java.lang.String custom3;

  public static final String SERIALIZED_NAME_FILE_NUMBER = "fileNumber";
  @SerializedName(SERIALIZED_NAME_FILE_NUMBER)
  private java.lang.String fileNumber;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private java.lang.String id;

  public static final String SERIALIZED_NAME_LAWYER = "lawyer";
  @SerializedName(SERIALIZED_NAME_LAWYER)
  private java.lang.String lawyer;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private java.lang.String name;

  public static final String SERIALIZED_NAME_NOTICE = "notice";
  @SerializedName(SERIALIZED_NAME_NOTICE)
  private java.lang.String notice;

  public static final String SERIALIZED_NAME_REASON = "reason";
  @SerializedName(SERIALIZED_NAME_REASON)
  private java.lang.String reason;

  public static final String SERIALIZED_NAME_SUBJECT_FIELD = "subjectField";
  @SerializedName(SERIALIZED_NAME_SUBJECT_FIELD)
  private java.lang.String subjectField;

  public RestfulCaseV1() {
  }

  public RestfulCaseV1 archived(Integer archived) {
    
    this.archived = archived;
    return this;
  }

   /**
   * Get archived
   * @return archived
  **/
  @javax.annotation.Nullable
  public Integer getArchived() {
    return archived;
  }


  public void setArchived(Integer archived) {
    this.archived = archived;
  }


  public RestfulCaseV1 assistant(java.lang.String assistant) {
    
    this.assistant = assistant;
    return this;
  }

   /**
   * Get assistant
   * @return assistant
  **/
  @javax.annotation.Nullable
  public java.lang.String getAssistant() {
    return assistant;
  }


  public void setAssistant(java.lang.String assistant) {
    this.assistant = assistant;
  }


  public RestfulCaseV1 claimNumber(java.lang.String claimNumber) {
    
    this.claimNumber = claimNumber;
    return this;
  }

   /**
   * Get claimNumber
   * @return claimNumber
  **/
  @javax.annotation.Nullable
  public java.lang.String getClaimNumber() {
    return claimNumber;
  }


  public void setClaimNumber(java.lang.String claimNumber) {
    this.claimNumber = claimNumber;
  }


  public RestfulCaseV1 claimValue(BigDecimal claimValue) {
    
    this.claimValue = claimValue;
    return this;
  }

   /**
   * Get claimValue
   * @return claimValue
  **/
  @javax.annotation.Nullable
  public BigDecimal getClaimValue() {
    return claimValue;
  }


  public void setClaimValue(BigDecimal claimValue) {
    this.claimValue = claimValue;
  }


  public RestfulCaseV1 custom1(java.lang.String custom1) {
    
    this.custom1 = custom1;
    return this;
  }

   /**
   * Get custom1
   * @return custom1
  **/
  @javax.annotation.Nullable
  public java.lang.String getCustom1() {
    return custom1;
  }


  public void setCustom1(java.lang.String custom1) {
    this.custom1 = custom1;
  }


  public RestfulCaseV1 custom2(java.lang.String custom2) {
    
    this.custom2 = custom2;
    return this;
  }

   /**
   * Get custom2
   * @return custom2
  **/
  @javax.annotation.Nullable
  public java.lang.String getCustom2() {
    return custom2;
  }


  public void setCustom2(java.lang.String custom2) {
    this.custom2 = custom2;
  }


  public RestfulCaseV1 custom3(java.lang.String custom3) {
    
    this.custom3 = custom3;
    return this;
  }

   /**
   * Get custom3
   * @return custom3
  **/
  @javax.annotation.Nullable
  public java.lang.String getCustom3() {
    return custom3;
  }


  public void setCustom3(java.lang.String custom3) {
    this.custom3 = custom3;
  }


  public RestfulCaseV1 fileNumber(java.lang.String fileNumber) {
    
    this.fileNumber = fileNumber;
    return this;
  }

   /**
   * Get fileNumber
   * @return fileNumber
  **/
  @javax.annotation.Nullable
  public java.lang.String getFileNumber() {
    return fileNumber;
  }


  public void setFileNumber(java.lang.String fileNumber) {
    this.fileNumber = fileNumber;
  }


  public RestfulCaseV1 id(java.lang.String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  public java.lang.String getId() {
    return id;
  }


  public void setId(java.lang.String id) {
    this.id = id;
  }


  public RestfulCaseV1 lawyer(java.lang.String lawyer) {
    
    this.lawyer = lawyer;
    return this;
  }

   /**
   * Get lawyer
   * @return lawyer
  **/
  @javax.annotation.Nullable
  public java.lang.String getLawyer() {
    return lawyer;
  }


  public void setLawyer(java.lang.String lawyer) {
    this.lawyer = lawyer;
  }


  public RestfulCaseV1 name(java.lang.String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  public java.lang.String getName() {
    return name;
  }


  public void setName(java.lang.String name) {
    this.name = name;
  }


  public RestfulCaseV1 notice(java.lang.String notice) {
    
    this.notice = notice;
    return this;
  }

   /**
   * Get notice
   * @return notice
  **/
  @javax.annotation.Nullable
  public java.lang.String getNotice() {
    return notice;
  }


  public void setNotice(java.lang.String notice) {
    this.notice = notice;
  }


  public RestfulCaseV1 reason(java.lang.String reason) {
    
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @javax.annotation.Nullable
  public java.lang.String getReason() {
    return reason;
  }


  public void setReason(java.lang.String reason) {
    this.reason = reason;
  }


  public RestfulCaseV1 subjectField(java.lang.String subjectField) {
    
    this.subjectField = subjectField;
    return this;
  }

   /**
   * Get subjectField
   * @return subjectField
  **/
  @javax.annotation.Nullable
  public java.lang.String getSubjectField() {
    return subjectField;
  }


  public void setSubjectField(java.lang.String subjectField) {
    this.subjectField = subjectField;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestfulCaseV1 restfulCaseV1 = (RestfulCaseV1) o;
    return Objects.equals(this.archived, restfulCaseV1.archived) &&
        Objects.equals(this.assistant, restfulCaseV1.assistant) &&
        Objects.equals(this.claimNumber, restfulCaseV1.claimNumber) &&
        Objects.equals(this.claimValue, restfulCaseV1.claimValue) &&
        Objects.equals(this.custom1, restfulCaseV1.custom1) &&
        Objects.equals(this.custom2, restfulCaseV1.custom2) &&
        Objects.equals(this.custom3, restfulCaseV1.custom3) &&
        Objects.equals(this.fileNumber, restfulCaseV1.fileNumber) &&
        Objects.equals(this.id, restfulCaseV1.id) &&
        Objects.equals(this.lawyer, restfulCaseV1.lawyer) &&
        Objects.equals(this.name, restfulCaseV1.name) &&
        Objects.equals(this.notice, restfulCaseV1.notice) &&
        Objects.equals(this.reason, restfulCaseV1.reason) &&
        Objects.equals(this.subjectField, restfulCaseV1.subjectField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(archived, assistant, claimNumber, claimValue, custom1, custom2, custom3, fileNumber, id, lawyer, name, notice, reason, subjectField);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestfulCaseV1 {\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("    assistant: ").append(toIndentedString(assistant)).append("\n");
    sb.append("    claimNumber: ").append(toIndentedString(claimNumber)).append("\n");
    sb.append("    claimValue: ").append(toIndentedString(claimValue)).append("\n");
    sb.append("    custom1: ").append(toIndentedString(custom1)).append("\n");
    sb.append("    custom2: ").append(toIndentedString(custom2)).append("\n");
    sb.append("    custom3: ").append(toIndentedString(custom3)).append("\n");
    sb.append("    fileNumber: ").append(toIndentedString(fileNumber)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lawyer: ").append(toIndentedString(lawyer)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    notice: ").append(toIndentedString(notice)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    subjectField: ").append(toIndentedString(subjectField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("archived");
    openapiFields.add("assistant");
    openapiFields.add("claimNumber");
    openapiFields.add("claimValue");
    openapiFields.add("custom1");
    openapiFields.add("custom2");
    openapiFields.add("custom3");
    openapiFields.add("fileNumber");
    openapiFields.add("id");
    openapiFields.add("lawyer");
    openapiFields.add("name");
    openapiFields.add("notice");
    openapiFields.add("reason");
    openapiFields.add("subjectField");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to RestfulCaseV1
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RestfulCaseV1.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RestfulCaseV1 is not found in the empty JSON string", RestfulCaseV1.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RestfulCaseV1.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RestfulCaseV1` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("assistant") != null && !jsonObj.get("assistant").isJsonNull()) && !jsonObj.get("assistant").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `assistant` to be a primitive type in the JSON string but got `%s`", jsonObj.get("assistant").toString()));
      }
      if ((jsonObj.get("claimNumber") != null && !jsonObj.get("claimNumber").isJsonNull()) && !jsonObj.get("claimNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `claimNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("claimNumber").toString()));
      }
      if ((jsonObj.get("custom1") != null && !jsonObj.get("custom1").isJsonNull()) && !jsonObj.get("custom1").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `custom1` to be a primitive type in the JSON string but got `%s`", jsonObj.get("custom1").toString()));
      }
      if ((jsonObj.get("custom2") != null && !jsonObj.get("custom2").isJsonNull()) && !jsonObj.get("custom2").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `custom2` to be a primitive type in the JSON string but got `%s`", jsonObj.get("custom2").toString()));
      }
      if ((jsonObj.get("custom3") != null && !jsonObj.get("custom3").isJsonNull()) && !jsonObj.get("custom3").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `custom3` to be a primitive type in the JSON string but got `%s`", jsonObj.get("custom3").toString()));
      }
      if ((jsonObj.get("fileNumber") != null && !jsonObj.get("fileNumber").isJsonNull()) && !jsonObj.get("fileNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fileNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fileNumber").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("lawyer") != null && !jsonObj.get("lawyer").isJsonNull()) && !jsonObj.get("lawyer").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lawyer` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lawyer").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("notice") != null && !jsonObj.get("notice").isJsonNull()) && !jsonObj.get("notice").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `notice` to be a primitive type in the JSON string but got `%s`", jsonObj.get("notice").toString()));
      }
      if ((jsonObj.get("reason") != null && !jsonObj.get("reason").isJsonNull()) && !jsonObj.get("reason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `reason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reason").toString()));
      }
      if ((jsonObj.get("subjectField") != null && !jsonObj.get("subjectField").isJsonNull()) && !jsonObj.get("subjectField").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subjectField` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subjectField").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RestfulCaseV1.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RestfulCaseV1' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RestfulCaseV1> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RestfulCaseV1.class));

       return (TypeAdapter<T>) new TypeAdapter<RestfulCaseV1>() {
           @Override
           public void write(JsonWriter out, RestfulCaseV1 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RestfulCaseV1 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RestfulCaseV1 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RestfulCaseV1
  * @throws IOException if the JSON string is invalid with respect to RestfulCaseV1
  */
  public static RestfulCaseV1 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RestfulCaseV1.class);
  }

 /**
  * Convert an instance of RestfulCaseV1 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

