/*
 * j-lawyer-io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * RestfulPlaceholderV6
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-14T23:02:59.563495701+01:00[Europe/Berlin]")
public class RestfulPlaceholderV6 {
  public static final String SERIALIZED_NAME_PLACE_HOLDER_KEY = "placeHolderKey";
  @SerializedName(SERIALIZED_NAME_PLACE_HOLDER_KEY)
  private java.lang.String placeHolderKey;

  public static final String SERIALIZED_NAME_PLACE_HOLDER_VALUE = "placeHolderValue";
  @SerializedName(SERIALIZED_NAME_PLACE_HOLDER_VALUE)
  private java.lang.String placeHolderValue;

  public RestfulPlaceholderV6() {
  }

  public RestfulPlaceholderV6 placeHolderKey(java.lang.String placeHolderKey) {
    
    this.placeHolderKey = placeHolderKey;
    return this;
  }

   /**
   * Get placeHolderKey
   * @return placeHolderKey
  **/
  @javax.annotation.Nullable
  public java.lang.String getPlaceHolderKey() {
    return placeHolderKey;
  }


  public void setPlaceHolderKey(java.lang.String placeHolderKey) {
    this.placeHolderKey = placeHolderKey;
  }


  public RestfulPlaceholderV6 placeHolderValue(java.lang.String placeHolderValue) {
    
    this.placeHolderValue = placeHolderValue;
    return this;
  }

   /**
   * Get placeHolderValue
   * @return placeHolderValue
  **/
  @javax.annotation.Nullable
  public java.lang.String getPlaceHolderValue() {
    return placeHolderValue;
  }


  public void setPlaceHolderValue(java.lang.String placeHolderValue) {
    this.placeHolderValue = placeHolderValue;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestfulPlaceholderV6 restfulPlaceholderV6 = (RestfulPlaceholderV6) o;
    return Objects.equals(this.placeHolderKey, restfulPlaceholderV6.placeHolderKey) &&
        Objects.equals(this.placeHolderValue, restfulPlaceholderV6.placeHolderValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(placeHolderKey, placeHolderValue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestfulPlaceholderV6 {\n");
    sb.append("    placeHolderKey: ").append(toIndentedString(placeHolderKey)).append("\n");
    sb.append("    placeHolderValue: ").append(toIndentedString(placeHolderValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("placeHolderKey");
    openapiFields.add("placeHolderValue");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to RestfulPlaceholderV6
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RestfulPlaceholderV6.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RestfulPlaceholderV6 is not found in the empty JSON string", RestfulPlaceholderV6.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RestfulPlaceholderV6.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RestfulPlaceholderV6` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("placeHolderKey") != null && !jsonObj.get("placeHolderKey").isJsonNull()) && !jsonObj.get("placeHolderKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `placeHolderKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("placeHolderKey").toString()));
      }
      if ((jsonObj.get("placeHolderValue") != null && !jsonObj.get("placeHolderValue").isJsonNull()) && !jsonObj.get("placeHolderValue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `placeHolderValue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("placeHolderValue").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RestfulPlaceholderV6.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RestfulPlaceholderV6' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RestfulPlaceholderV6> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RestfulPlaceholderV6.class));

       return (TypeAdapter<T>) new TypeAdapter<RestfulPlaceholderV6>() {
           @Override
           public void write(JsonWriter out, RestfulPlaceholderV6 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RestfulPlaceholderV6 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RestfulPlaceholderV6 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RestfulPlaceholderV6
  * @throws IOException if the JSON string is invalid with respect to RestfulPlaceholderV6
  */
  public static RestfulPlaceholderV6 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RestfulPlaceholderV6.class);
  }

 /**
  * Convert an instance of RestfulPlaceholderV6 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

