name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package

    - name: Find WAR File
      id: find_war
      run: echo "::set-output name=filename::$(find ./target -name '*.war' -printf '%f')"

    - name: Upload Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.repository.releases_url }}
        asset_path: ./target/${{ steps.find_war.outputs.filename }}
        asset_name: ${{ steps.find_war.outputs.filename }}
        asset_content_type: application/java-archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
